---
title: "2021 Selection Analysis"

output: 
  html_document: 
    toc: yes
    theme: cerulean
---




```{r}
library(sf)
library(stringr)
library(tidyverse)
library(readxl)
library(magrittr)
library(huxtable)
library(broom)
```



# Geo data
```{r setup, include=FALSE}
my_path_wahlkreise <- "~/Documents/Github/R-Prediction/btw21_geometrie_wahlkreise_shp/Geometrie_Wahlkreise_20DBT.shp"
file.exists(my_path_wahlkreise)
```

```{r}
wahlkreise_shp <- st_read(my_path_wahlkreise)
```

```{r}
glimpse(wahlkreise_shp)
```

```{r}
wahlkreise_shp %>%
  ggplot() +
  geom_sf()
```

```{r}
wahlkreise_shp %>%
  ggplot() +
  geom_sf(fill = "grey40") +
  theme_void()
```

# unemployment ratios

```{r}
unemp_file <- "~/Documents/Github/R-Prediction/btw21_Strukturdaten.csv"

file.exists(unemp_file)
```


```{r}
unemp_de_raw <- read_delim(unemp_file,
    ";", escape_double = FALSE,
    locale = locale(decimal_mark = ",",
        grouping_mark = "."),
    trim_ws = TRUE,
    skip = 8)  # skipt the first 8 rows
```




```{r}
unemp_names <- names(unemp_de_raw)

unemp_de <- unemp_de_raw

names(unemp_de) <- paste0("V",1:ncol(unemp_de))
```
The important columns are:




```{r}
unemp_de <- unemp_de %>%
  rename(state = V1,
         area_nr = V2,
         area_name = V3,
         for_prop = V8,
         pop_move = V11,
         pop_migr_background = V19,
         income = V26,
         unemp = V47)  
```

# AfD election results

```{r}
elec_file <- "~/Documents/Github/R-Prediction/kerg.csv"
file.exists(elec_file)
```


```{r}
library(readr)
elec_results <- read_csv(elec_file)
```



```{r}

afd_prop <- elec_results %>%
  select(1, 2, 46, 18) %>%
  rename(afd_votes = AfD3,
         area_nr = Nr,
         area_name = Gebiet,
         votes_total = Waehler_gueltige_Zweitstimmen_vorlauefig) %>%
  mutate(afd_prop = afd_votes / votes_total) %>%
  na.omit
```


```{r}
View()
```



```{r}

```


```{r}

```



```{r}

```


```{r}

```



```{r}

```


```{r}

```







